export const productsMock = [
    {
        id: 1,
        name: "Cable galvanizado reforzado para cercos rurales de alta resistencia",
        category: "Ferretería",
        stock: 125,
        price: 18500,
        image: "/src/img/products/cable_galvanizado.jpg",
    },
    {
        id: 2,
        name: "Cemento Portland CP40 x 50 kg",
        category: "Construcción",
        stock: 42,
        price: 9200,
        image: "/src/img/products/cemento.jpg",
    },
    {
        id: 3,
        name: "Cetol Classic Satinado Protector para Madera 4 L",
        category: "Pinturería",
        stock: 8,
        price: 48900,
        image: "/src/img/products/cetol.jpg",
    },
    {
        id: 4,
        name: "Ladrillo Cerámico Portante 18x19x33 cm",
        category: "Construcción",
        stock: 650,
        price: 1350,
        image: "/src/img/products/ladrilo.jpg",
    },
    {
        id: 5,
        name: "Cable Galvanizado Trenzado 6 mm para Alambrados",
        category: "Ferretería",
        stock: 87,
        price: 27300,
        image: "/src/img/products/cable_galvanizado.jpg",
    },
    {
        id: 6,
        name: "Cemento de Albañilería Plasticor Bolsa 40 kg",
        category: "Construcción",
        stock: 31,
        price: 7800,
        image: "/src/img/products/cemento.jpg",
    },
    {
        id: 7,
        name: "Cetol Deck Protector para Madera Exterior 1 L",
        category: "Pinturería",
        stock: 15,
        price: 21900,
        image: "/src/img/products/cetol.jpg",
    },
    {
        id: 8,
        name: "Ladrillo Común de Campo para Muros y Cerramientos",
        category: "Construcción",
        stock: 1200,
        price: 950,
        image: "/src/img/products/ladrilo.jpg",
    },
];

export const categoriesMock = [
    {name: "Ferretería", description: "", color: "#DE1240"},
    {name: "Construcción", description: "", color: "#CB3999"},
    {name: "Pinturería", description: "", color: "#39589E"}
]

export const usersMock = [
	{
		name: "Ignacio",
		lastname: "Alonso",
		username: "ignacio.admin",
		password: "Admin1234*",
		isAdmin: true,
		isAllowed: true,
	},
	{
		name: "Juan",
		lastname: "Pérez",
		username: "juan.perez",
		password: "User1234*",
		isAdmin: false,
		isAllowed: true,
	},
	{
		name: "Pedro",
		lastname: "Martin",
		username: "pedro.martin",
		password: "User1234*",
		isAdmin: false,
		isAllowed: false,
	},
];

export const ordersMock = [
    // =========================
    // juan.perez
    // =========================
    {
        id: 1,
        username: "juan.perez",
        total: 18500,
        date: "10/6/2026, 09:15:22",
        products: [
            {
                id: 1,
                product: "Cable galvanizado reforzado para cercos rurales de alta resistencia",
                category: "Ferretería",
                price: 18500,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
        ],
    },
    {
        id: 2,
        username: "juan.perez",
        total: 10450,
        date: "11/6/2026, 14:32:10",
        products: [
            {
                id: 2,
                product: "Cemento Portland CP40 x 50 kg",
                category: "Construcción",
                price: 9200,
                quantity: 1,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 8,
                product: "Ladrillo Común de Campo para Muros y Cerramientos",
                category: "Construcción",
                price: 950,
                quantity: 1,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 3,
        username: "juan.perez",
        total: 32950,
        date: "12/6/2026, 18:45:55",
        products: [
            {
                id: 5,
                product: "Cable Galvanizado Trenzado 6 mm para Alambrados",
                category: "Ferretería",
                price: 27300,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 4,
                product: "Ladrillo Cerámico Portante 18x19x33 cm",
                category: "Construcción",
                price: 1350,
                quantity: 4,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 4,
        username: "juan.perez",
        total: 66900,
        date: "14/6/2026, 11:20:33",
        products: [
            {
                id: 3,
                product: "Cetol Classic Satinado Protector para Madera 4 L",
                category: "Pinturería",
                price: 48900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
            {
                id: 6,
                product: "Cemento de Albañilería Plasticor Bolsa 40 kg",
                category: "Construcción",
                price: 7800,
                quantity: 1,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 4,
                product: "Ladrillo Cerámico Portante 18x19x33 cm",
                category: "Construcción",
                price: 1350,
                quantity: 3,
                image: "/src/img/products/ladrilo.jpg",
            },
            {
                id: 8,
                product: "Ladrillo Común de Campo para Muros y Cerramientos",
                category: "Construcción",
                price: 950,
                quantity: 2,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 5,
        username: "juan.perez",
        total: 119700,
        date: "16/6/2026, 16:05:47",
        products: [
            {
                id: 1,
                product: "Cable galvanizado reforzado para cercos rurales de alta resistencia",
                category: "Ferretería",
                price: 18500,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 2,
                product: "Cemento Portland CP40 x 50 kg",
                category: "Construcción",
                price: 9200,
                quantity: 2,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 3,
                product: "Cetol Classic Satinado Protector para Madera 4 L",
                category: "Pinturería",
                price: 48900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
            {
                id: 4,
                product: "Ladrillo Cerámico Portante 18x19x33 cm",
                category: "Construcción",
                price: 1350,
                quantity: 5,
                image: "/src/img/products/ladrilo.jpg",
            },
            {
                id: 7,
                product: "Cetol Deck Protector para Madera Exterior 1 L",
                category: "Pinturería",
                price: 21900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
        ],
    },

    // =========================
    // ignacio.admin
    // =========================
    {
        id: 6,
        username: "ignacio.admin",
        total: 48900,
        date: "10/6/2026, 12:10:15",
        products: [
            {
                id: 3,
                product: "Cetol Classic Satinado Protector para Madera 4 L",
                category: "Pinturería",
                price: 48900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
        ],
    },
    {
        id: 7,
        username: "ignacio.admin",
        total: 35100,
        date: "11/6/2026, 17:42:28",
        products: [
            {
                id: 6,
                product: "Cemento de Albañilería Plasticor Bolsa 40 kg",
                category: "Construcción",
                price: 7800,
                quantity: 3,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 8,
                product: "Ladrillo Común de Campo para Muros y Cerramientos",
                category: "Construcción",
                price: 950,
                quantity: 12,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 8,
        username: "ignacio.admin",
        total: 85800,
        date: "13/6/2026, 08:55:02",
        products: [
            {
                id: 5,
                product: "Cable Galvanizado Trenzado 6 mm para Alambrados",
                category: "Ferretería",
                price: 27300,
                quantity: 2,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 4,
                product: "Ladrillo Cerámico Portante 18x19x33 cm",
                category: "Construcción",
                price: 1350,
                quantity: 23,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 9,
        username: "ignacio.admin",
        total: 78950,
        date: "15/6/2026, 15:23:51",
        products: [
            {
                id: 1,
                product: "Cable galvanizado reforzado para cercos rurales de alta resistencia",
                category: "Ferretería",
                price: 18500,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 2,
                product: "Cemento Portland CP40 x 50 kg",
                category: "Construcción",
                price: 9200,
                quantity: 2,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 4,
                product: "Ladrillo Cerámico Portante 18x19x33 cm",
                category: "Construcción",
                price: 1350,
                quantity: 5,
                image: "/src/img/products/ladrilo.jpg",
            },
        ],
    },
    {
        id: 10,
        username: "ignacio.admin",
        total: 129250,
        date: "18/6/2026, 19:17:25",
        products: [
            {
                id: 1,
                product: "Cable galvanizado reforzado para cercos rurales de alta resistencia",
                category: "Ferretería",
                price: 18500,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 3,
                product: "Cetol Classic Satinado Protector para Madera 4 L",
                category: "Pinturería",
                price: 48900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
            {
                id: 5,
                product: "Cable Galvanizado Trenzado 6 mm para Alambrados",
                category: "Ferretería",
                price: 27300,
                quantity: 1,
                image: "/src/img/products/cable_galvanizado.jpg",
            },
            {
                id: 6,
                product: "Cemento de Albañilería Plasticor Bolsa 40 kg",
                category: "Construcción",
                price: 7800,
                quantity: 1,
                image: "/src/img/products/cemento.jpg",
            },
            {
                id: 7,
                product: "Cetol Deck Protector para Madera Exterior 1 L",
                category: "Pinturería",
                price: 21900,
                quantity: 1,
                image: "/src/img/products/cetol.jpg",
            },
        ],
    },
];

export const configurationMock = {
    sessionExpiring: 72,
    pagination: {
        catalog: 10,
        profile: 8,
        admin: 12,
    },
    minimumPurchaseAmount: 5000,
    stock: {
        lowThreshold: 10,
        mediumThreshold: 50,
        highThreshold: 100,
    },
};